[package]
name = "alexandria"
version = "0.1.0"
description = "Starknet utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/"

[dependencies]
starknet = ">=2.1.0"

[scripts]
all = "scarb build && scarb test"